Data cleaning and preparation for the 2016 CES dataset

#### Workplace setup

In [ ]:
# workplace setup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive

#### Data loading

In [ ]:
# load the data from Harvard Dataverse
!wget --no-check-certificate "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/GDF6Z0/JPMOZZ" -O CCES16_Common_OUTPUT_Feb2018_VV.tab
ces16_raw = pd.read_csv("CCES16_Common_OUTPUT_Feb2018_VV.tab", sep="\t")

--2025-08-24 18:01:53--  https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/GDF6Z0/JPMOZZ
Resolving dataverse.harvard.edu (dataverse.harvard.edu)... 52.205.237.141, 52.6.5.183, 3.237.56.51
Connecting to dataverse.harvard.edu (dataverse.harvard.edu)|52.205.237.141|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://dvn-cloud.s3.amazonaws.com/10.7910/DVN/GDF6Z0/161810294da-1d1cff04a505?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27CCES16_Common_OUTPUT_Feb2018_VV.tab&response-content-type=text%2Ftab-separated-values&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250824T180154Z&X-Amz-SignedHeaders=host&X-Amz-Credential=AKIAIEJ3NV7UYCSRJC7A%2F20250824%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Expires=3600&X-Amz-Signature=ff9920f15c9e44c7e98f9aabe6c407c0a7528ecde17f106462045f41df92115a [following]
--2025-08-24 18:01:54--  https://dvn-cloud.s3.amazonaws.com/10.7910/DVN/GDF6Z0/161810294da-1d1cff04a505?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27CCES16_Common_OUTPUT_Feb2018_VV.tab&response-content-type=text%2Ftab-separated-values&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250824T180154Z&X-Amz-SignedHeaders=host&X-Amz-Credential=AKIAIEJ3NV7UYCSRJC7A%2F20250824%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Expires=3600&X-Amz-Signature=ff9920f15c9e44c7e98f9aabe6c407c0a7528ecde17f106462045f41df92115a
Resolving dvn-cloud.s3.amazonaws.com (dvn-cloud.s3.amazonaws.com)... 52.216.208.177, 52.217.196.209, 52.216.33.57, ...
Connecting to dvn-cloud.s3.amazonaws.com (dvn-cloud.s3.amazonaws.com)|52.216.208.177|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 134761608 (129M) [text/tab-separated-values]
Saving to: ‘CCES16_Common_OUTPUT_Feb2018_VV.tab’

CCES16_Common_OUTPU 100%[===================>] 128.52M  35.4MB/s    in 3.6s

2025-08-24 18:01:58 (35.4 MB/s) - ‘CCES16_Common_OUTPUT_Feb2018_VV.tab’ saved [134761608/134761608]

/tmp/ipython-input-1654278582.py:3: DtypeWarning: Columns (46,47,48,49,50,51,52,53,54,55,371,373,374,375,376,377,378,379,380,381,382,383,385,386,388,389,390,391,393,394,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,419,420,422,423,424,425,426,427,430,432,436,439,441,443,445,446,447,448,449,450,451,452,453,454,455,456,458,460,462,486,487,493,494,513,515,520,522,526,527,528,533,534,535,541,542,543,544,545,559,560) have mixed types. Specify dtype option on import or set low_memory=False.
  ces16_raw = pd.read_csv("CCES16_Common_OUTPUT_Feb2018_VV.tab", sep="\t")

In [ ]:
ces16_raw.head()

,V101,commonweight_vv,commonweight_vv_post,commonweight_vv_lgbt,commonweight,commonweight_post,tookpost,lookupzip,inputstate,cdid113,...,CL_E2016PPEP,CL_E2016PPVM,CL_E2016PEP,CL_E2016PVM,starttime_pre,endtime_pre,starttime_post,endtime_post,dma,dmaname
0,222168628,1.344214,1.042267,1.195346,0.944967,0.730450,1,3442,33,2,...,NaN,NaN,NaN,NaN,2016-10-20 05:05:44.887,2016-10-20 05:36:38.850,2016-11-16 06:24:32.895,2016-11-16 06:40:18.810,NaN,NaN
1,273691199,1.182352,1.280103,1.280565,0.767256,0.892838,1,70118,22,2,...,NaN,NaN,NaN,NaN,2016-10-23 14:54:58.548,2016-10-24 14:20:41.711,2016-11-30 14:02:55.143,2016-11-30 14:09:26.931,622.0,NEW ORLEANS
2,284214415,0.217396,NaN,0.248930,0.090604,0.000000,0,63851,29,8,...,NaN,NaN,NaN,NaN,2016-10-29 06:54:12.797,2016-10-29 07:24:44.759,NaN,NaN,632.0,PADUCAH-CAPE GIRARD-HARSBG
3,287557695,0.532320,NaN,0.928750,0.142583,0.000000,0,36703,1,7,...,NaN,NaN,NaN,NaN,2016-10-27 11:06:21.322,2016-10-27 11:26:00.051,NaN,NaN,698.0,MONTGOMERY-SELMA
4,290387662,1.261106,1.092519,1.161894,1.206498,1.019007,1,80526,8,2,...,NaN,NaN,NaN,NaN,2016-10-10 10:56:31.061,2016-10-10 11:14:12.215,2016-11-18 09:09:28.044,2016-11-18 09:21:05.905,751.0,DENVER

## Subset data to include only relevant cols

In [ ]:
# select relevant columns
ces16_subset = ces16_raw[[
    # 'CC16_364b', # presidential vote
    'CC16_364c', # preferred presidential candidate
    'CC16_410a', # who they voted for
    'race', # self reported race
    'birthyr', # year respondent was born
    'gender', # gender identity
    'educ', # highest level of educational attainment
    'inputstate', # state that respondent lives in
    'CC16_302', # national economy over the past year
    'CC16_303', # household income past 4yrs
    'CC16_320a', # obama (incumbent pres) approval
    'tookpost', # whether respondent participated in post election wave
    'commonweight'  # weight of respondent common,
]]
ces16_subset

,CC16_364c,CC16_410a,race,birthyr,gender,educ,inputstate,CC16_302,CC16_303,CC16_320a,tookpost,commonweight
0,1.0,1.0,1,1969,2,2,33,3.0,2.0,4.0,1,0.944967
1,1.0,1.0,1,1994,2,2,22,4.0,3.0,3.0,1,0.767256
2,2.0,NaN,2,1964,2,2,29,5.0,2.0,1.0,0,0.090604
3,7.0,NaN,2,1988,2,2,1,4.0,4.0,1.0,0,0.142583
4,2.0,2.0,1,1982,2,5,8,2.0,2.0,1.0,1,1.206498
...,...,...,...,...,...,...,...,...,...,...,...,...
64595,1.0,NaN,2,1990,1,3,36,1.0,2.0,1.0,0,1.858637
64596,6.0,NaN,1,1986,2,1,8,6.0,3.0,5.0,0,0.518973
64597,2.0,NaN,1,1978,1,2,22,2.0,2.0,2.0,0,7.441724
64598,2.0,NaN,1,1987,1,2,44,2.0,1.0,1.0,0,0.842803
64599,7.0,NaN,1,1974,1,2,1,5.0,5.0,5.0,0,0.209824

In [ ]:
# presidential vote counts
ces16_subset['CC16_364c'].value_counts()

CC16_364c
2.0    27502
1.0    19227
7.0     6536
6.0     3312
3.0     3145
5.0     1880
4.0     1400
Name: count, dtype: int64

In [ ]:
ces16_410a = ces16_subset['CC16_410a'].value_counts()
ces16_410a

CC16_410a
2.0       21841
1.0       18461
3.0        1811
5.0        1109
4.0         897
2           295
1           293
7.0         222
8.0         163
6.0          81
5            27
3            18
4            16
7             7
__NA__        1
Name: count, dtype: int64

In [ ]:
ces16_subset2 = ces16_subset[
    (ces16_subset['race'] <= 8) &
    (ces16_subset['gender'] <= 2) &
    (ces16_subset['CC16_320a'] < 8) &
    (ces16_subset['CC16_303'] < 8) &
    (ces16_subset['CC16_302'] < 8) &
    (ces16_subset['CC16_410a'].isin([1.0, 2.0])) &
    (ces16_subset['birthyr'].notna()) &
    (ces16_subset['educ'] <= 6) &
    (ces16_subset['inputstate'].notna()) &
    (ces16_subset['tookpost'] == 1)
]

In [ ]:
ces16_subset2

,CC16_364c,CC16_410a,race,birthyr,gender,educ,inputstate,CC16_302,CC16_303,CC16_320a,tookpost,commonweight
0,1.0,1.0,1,1969,2,2,33,3.0,2.0,4.0,1,0.944967
1,1.0,1.0,1,1994,2,2,22,4.0,3.0,3.0,1,0.767256
4,2.0,2.0,1,1982,2,5,8,2.0,2.0,1.0,1,1.206498
6,1.0,1.0,1,1962,1,2,48,3.0,3.0,4.0,1,1.112030
8,1.0,1.0,1,1963,1,2,13,4.0,4.0,4.0,1,2.414978
...,...,...,...,...,...,...,...,...,...,...,...,...
64442,2.0,2.0,2,1992,2,3,28,6.0,5.0,2.0,1,0.834926
64443,NaN,2.0,1,1957,1,1,6,2.0,5.0,3.0,1,8.756484
64445,2.0,2.0,1,1954,1,2,25,2.0,2.0,1.0,1,0.740749
64447,2.0,2.0,1,1953,1,2,20,2.0,3.0,1.0,1,1.494045
64453,2.0,2.0,1,1959,1,2,53,2.0,2.0,1.0,1,1.602087

In [ ]:
ces16_subset2['CC16_364c'].value_counts()

CC16_364c
2.0    19373
1.0    14973
7.0     2907
3.0      719
5.0      640
4.0      314
6.0      135
Name: count, dtype: int64

In [ ]:
ces16_subset2['CC16_410a'].value_counts()

CC16_410a
2.0    21759
1.0    18421
Name: count, dtype: int64

## Recode numeric variables into categorical variables that match the 2020 and 2024 datasets

In [ ]:
ces16_df = ces16_subset2.copy().drop(columns=['tookpost'])
# recode numeric variables
# state
fips_to_state = {
    1: "Alabama",
    2: "Alaska",
    4: "Arizona",
    5: "Arkansas",
    6: "California",
    8: "Colorado",
    9: "Connecticut",
    10: "Delaware",
    11: "District of Columbia",
    12: "Florida",
    13: "Georgia",
    15: "Hawaii",
    16: "Idaho",
    17: "Illinois",
    18: "Indiana",
    19: "Iowa",
    20: "Kansas",
    21: "Kentucky",
    22: "Louisiana",
    23: "Maine",
    24: "Maryland",
    25: "Massachusetts",
    26: "Michigan",
    27: "Minnesota",
    28: "Mississippi",
    29: "Missouri",
    30: "Montana",
    31: "Nebraska",
    32: "Nevada",
    33: "New Hampshire",
    34: "New Jersey",
    35: "New Mexico",
    36: "New York",
    37: "North Carolina",
    38: "North Dakota",
    39: "Ohio",
    40: "Oklahoma",
    41: "Oregon",
    42: "Pennsylvania",
    44: "Rhode Island",
    45: "South Carolina",
    46: "South Dakota",
    47: "Tennessee",
    48: "Texas",
    49: "Utah",
    50: "Vermont",
    51: "Virginia",
    53: "Washington",
    54: "West Virginia",
    55: "Wisconsin",
    56: "Wyoming"
}

# gender
gender_map_numeric = {
    1: "Male",
    2: "Female"
}

# race
race_map_numeric = {
    1: 'White',
    2: 'Black',
    3: 'Hispanic',
    4: 'All Other Races',
    5: 'All Other Races',
    6: 'All Other Races',
    7: 'All Other Races',
    8: 'All Other Races'
}

# economy
econ_map_numeric = {
    1: 'Gotten much better',
    2: 'Gotten better',
    3: 'Stayed the same',
    4: 'Gotten worse',
    5: 'Gotten much worse',
    6: 'Not sure'
}

# income
income_map_numeric = {
    1: 'Increased a lot',
    2: 'Increaseed somewhat',
    3: 'Stayed the same',
    4: 'Decreased somewhat',
    5: 'Decreased a lot'
}

# obama approval
obama_map_numeric = {
    1: 'Strongly approve',
    2: 'Somewhat approve',
    3: 'Somewhat disapprove',
    4: 'Strongly disapprove',
    5: 'Not sure'
}

educ_map_numeric = {
    1: 'No HS',
    2: 'High school graduate',
    3: 'Some college',
    4: '2-year',
    5: '4-year',
    6: 'Post-grad'
}

# recode numeric variables
ces16_df['inputstate'] = ces16_df['inputstate'].map(fips_to_state)
ces16_df['gender'] = ces16_df['gender'].map(gender_map_numeric)
ces16_df['race'] = ces16_df['race'].map(race_map_numeric)
ces16_df['CC16_302'] = ces16_df['CC16_302'].map(econ_map_numeric)
ces16_df['CC16_303'] = ces16_df['CC16_303'].map(income_map_numeric)
ces16_df['CC16_320a'] = ces16_df['CC16_320a'].map(obama_map_numeric)
ces16_df['educ'] = ces16_df['educ'].map(educ_map_numeric)

# create an age variable
ces16_df['age'] = 2016 - ces16_df['birthyr']

# create a vote_clinton variable
ces16_df['presvote16'] = np.where(ces16_df['CC16_410a'] == 1.0, 'Donald Trump (Republican)', 'Hillary Clinton (Democrat)')
ces16_df['vote_clinton'] = np.where(ces16_df['CC16_410a'] == 2.0, 1, 0)
ces16_df['vote_trump'] = np.where(ces16_df['CC16_410a'] == 1.0, 1, 0)

In [ ]:
ces16_df

,CC16_364c,CC16_410a,race,birthyr,gender,educ,inputstate,CC16_302,CC16_303,CC16_320a,commonweight,age,presvote16,vote_clinton,vote_trump
0,1.0,1.0,White,1969,Female,High school graduate,New Hampshire,Stayed the same,Increaseed somewhat,Strongly disapprove,0.944967,47,Donald Trump (Republican),0,1
1,1.0,1.0,White,1994,Female,High school graduate,Louisiana,Gotten worse,Stayed the same,Somewhat disapprove,0.767256,22,Donald Trump (Republican),0,1
4,2.0,2.0,White,1982,Female,4-year,Colorado,Gotten better,Increaseed somewhat,Strongly approve,1.206498,34,Hillary Clinton (Democrat),1,0
6,1.0,1.0,White,1962,Male,High school graduate,Texas,Stayed the same,Stayed the same,Strongly disapprove,1.112030,54,Donald Trump (Republican),0,1
8,1.0,1.0,White,1963,Male,High school graduate,Georgia,Gotten worse,Decreased somewhat,Strongly disapprove,2.414978,53,Donald Trump (Republican),0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64442,2.0,2.0,Black,1992,Female,Some college,Mississippi,Not sure,Decreased a lot,Somewhat approve,0.834926,24,Hillary Clinton (Democrat),1,0
64443,NaN,2.0,White,1957,Male,No HS,California,Gotten better,Decreased a lot,Somewhat disapprove,8.756484,59,Hillary Clinton (Democrat),1,0
64445,2.0,2.0,White,1954,Male,High school graduate,Massachusetts,Gotten better,Increaseed somewhat,Strongly approve,0.740749,62,Hillary Clinton (Democrat),1,0
64447,2.0,2.0,White,1953,Male,High school graduate,Kansas,Gotten better,Stayed the same,Strongly approve,1.494045,63,Hillary Clinton (Democrat),1,0
64453,2.0,2.0,White,1959,Male,High school graduate,Washington,Gotten better,Increaseed somewhat,Strongly approve,1.602087,57,Hillary Clinton (Democrat),1,0

In [ ]:
# do the age bracket variable
ces16_df['age_bracket'] = pd.cut(
    ces16_df['age'],
    bins=[17, 24, 34, 44, 54, 64, 74, 100],
    labels=[
        '18–24', '25–34', '35–44', '45–54', '55–64', '65–74', '75+'
    ]
)

# region
race_map = {
    'White': 'White',
    'Black': 'Black',
    'Hispanic': 'Hispanic',
    'Asian': 'All Other Races',
    'Two or more races': 'All Other Races',
    'Other': 'All Other Races',
    'Native American': 'All Other Races',
    'Middle Eastern': 'All Other Races'
}
state_to_region = {
    # Northeast
    "Connecticut": "Northeast",
    "Massachusetts": "Northeast",
    "New York": "Northeast",
    "New Hampshire": "Northeast",
    "Rhode Island": "Northeast",
    "Maine": "Northeast",
    "New Jersey": "Northeast",
    "Pennsylvania": "Northeast",
    "Vermont": "Northeast",

    # Midwest
    "Ohio": "Midwest",
    "South Dakota": "Midwest",
    "Indiana": "Midwest",
    "Michigan": "Midwest",
    "Illinois": "Midwest",
    "Kansas": "Midwest",
    "Missouri": "Midwest",
    "Minnesota": "Midwest",
    "Wisconsin": "Midwest",
    "Iowa": "Midwest",
    "Nebraska": "Midwest",
    "North Dakota": "Midwest",

    # South
    "Virginia": "South",
    "Texas": "South",
    "Georgia": "South",
    "Arkansas": "South",
    "Louisiana": "South",
    "Florida": "South",
    "Alabama": "South",
    "South Carolina": "South",
    "Maryland": "South",
    "North Carolina": "South",
    "West Virginia": "South",
    "Mississippi": "South",
    "Oklahoma": "South",
    "Tennessee": "South",
    "Delaware": "South",
    "District of Columbia": "South",
    "Kentucky": "South",

    # West (13)
    "California": "West",
    "Washington": "West",
    "Arizona": "West",
    "Colorado": "West",
    "Utah": "West",
    "Oregon": "West",
    "New Mexico": "West",
    "Montana": "West",
    "Nevada": "West",
    "Alaska": "West",
    "Idaho": "West",
    "Hawaii": "West",
    "Wyoming": "West",
}
ces16_df['region'] = ces16_df['inputstate'].map(state_to_region)

In [ ]:
ces16_df

,CC16_364c,CC16_410a,race,birthyr,gender,educ,inputstate,CC16_302,CC16_303,CC16_320a,commonweight,age,presvote16,vote_clinton,vote_trump,age_bracket,region
0,1.0,1.0,White,1969,Female,High school graduate,New Hampshire,Stayed the same,Increaseed somewhat,Strongly disapprove,0.944967,47,Donald Trump (Republican),0,1,45–54,Northeast
1,1.0,1.0,White,1994,Female,High school graduate,Louisiana,Gotten worse,Stayed the same,Somewhat disapprove,0.767256,22,Donald Trump (Republican),0,1,18–24,South
4,2.0,2.0,White,1982,Female,4-year,Colorado,Gotten better,Increaseed somewhat,Strongly approve,1.206498,34,Hillary Clinton (Democrat),1,0,25–34,West
6,1.0,1.0,White,1962,Male,High school graduate,Texas,Stayed the same,Stayed the same,Strongly disapprove,1.112030,54,Donald Trump (Republican),0,1,45–54,South
8,1.0,1.0,White,1963,Male,High school graduate,Georgia,Gotten worse,Decreased somewhat,Strongly disapprove,2.414978,53,Donald Trump (Republican),0,1,45–54,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64442,2.0,2.0,Black,1992,Female,Some college,Mississippi,Not sure,Decreased a lot,Somewhat approve,0.834926,24,Hillary Clinton (Democrat),1,0,18–24,South
64443,NaN,2.0,White,1957,Male,No HS,California,Gotten better,Decreased a lot,Somewhat disapprove,8.756484,59,Hillary Clinton (Democrat),1,0,55–64,West
64445,2.0,2.0,White,1954,Male,High school graduate,Massachusetts,Gotten better,Increaseed somewhat,Strongly approve,0.740749,62,Hillary Clinton (Democrat),1,0,55–64,Northeast
64447,2.0,2.0,White,1953,Male,High school graduate,Kansas,Gotten better,Stayed the same,Strongly approve,1.494045,63,Hillary Clinton (Democrat),1,0,55–64,Midwest
64453,2.0,2.0,White,1959,Male,High school graduate,Washington,Gotten better,Increaseed somewhat,Strongly approve,1.602087,57,Hillary Clinton (Democrat),1,0,55–64,West

In [ ]:
# rename columns
ces16_df = ces16_df.rename(columns={'inputstate': 'state',
                         'CC16_302': 'econ_past_year',
                         'CC16_303': 'income_past_4yrs',
                         'CC16_320a': 'incumbent_pres_approval',
                         })

In [ ]:
# make columns categorical
gender_categories = pd.CategoricalDtype(categories=['Male', 'Female'], ordered=True)
age_categories = pd.CategoricalDtype(categories=['18–24', '25–34', '35–44', '45–54', '55–64', '65–74', '75+'], ordered=True)

ces16_df['presvote16'] = ces16_df['presvote16'].astype('category')
ces16_df['age_bracket'] = ces16_df['age_bracket'].astype(age_categories)
ces16_df['gender'] = ces16_df['gender'].astype(gender_categories)
ces16_df['race'] = ces16_df['race'].astype('category')
# ces16_df['state'] = ces16_df['state'].astype('category')
ces16_df['region'] = ces16_df['region'].astype('category')
ces16_df['econ_past_year'] = ces16_df['econ_past_year'].astype('category')
ces16_df['income_past_4yrs'] = ces16_df['income_past_4yrs'].astype('category')
ces16_df['incumbent_pres_approval'] = ces16_df['incumbent_pres_approval'].astype('category')

In [ ]:
ces16_clean = ces16_df[['presvote16',
                        'vote_clinton',
                        'vote_trump',
                        'age_bracket',
                        'race',
                        'gender',
                        'educ',
                        'state',
                        'region',
                        'econ_past_year',
                        'income_past_4yrs',
                        'incumbent_pres_approval'
                        ]]

In [ ]:
ces16_clean['presvote16'].value_counts()

presvote16
Hillary Clinton (Democrat)    21759
Donald Trump (Republican)     18421
Name: count, dtype: int64

In [ ]:
ces16_clean['vote_clinton'].value_counts()

vote_clinton
1    21759
0    18421
Name: count, dtype: int64

In [ ]:
# create dummies
ces16_clean2 = ces16_clean.copy().drop(columns=['presvote16'])

def create_dummy_interaction(col1, col2):
  result = pd.DataFrame()
  col1_dummies = pd.get_dummies(col1, drop_first=True)
  col2_dummies = pd.get_dummies(col2, drop_first=True)
  for col1_val in col1_dummies.columns:
    for col2_val in col2_dummies.columns:
      result[f'{col1_val}_{col2_val}'] = col1_dummies[col1_val] * col2_dummies[col2_val]
  return result

# create the interaction dummies
race_gender_interaction_terms = create_dummy_interaction(ces16_clean2['race'], ces16_clean2['gender'])
race_educ_interaction_terms = create_dummy_interaction(ces16_clean2['race'], ces16_clean2['educ'])
race_region_interaction_terms = create_dummy_interaction(ces16_clean2['race'], ces16_clean2['region'])

ces16_dummies = pd.concat([
    pd.get_dummies(ces16_clean2, drop_first=True),
    race_gender_interaction_terms,
    race_educ_interaction_terms,
    race_region_interaction_terms
], axis=1)

In [ ]:
ces16_dummies

,vote_clinton,vote_trump,age_bracket_25–34,age_bracket_35–44,age_bracket_45–54,age_bracket_55–64,age_bracket_65–74,age_bracket_75+,race_Black,race_Hispanic,...,White_Some college,Black_Northeast,Black_South,Black_West,Hispanic_Northeast,Hispanic_South,Hispanic_West,White_Northeast,White_South,White_West
0,0,1,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,0,1,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,1,0,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
6,0,1,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
8,0,1,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64442,1,0,False,False,False,False,False,False,True,False,...,False,False,True,False,False,False,False,False,False,False
64443,1,0,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
64445,1,0,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
64447,1,0,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
64453,1,0,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [ ]:
# write parquets to download locally
ces16_clean.to_parquet("ces16_clean.parquet")
ces16_dummies.to_parquet("ces16_analysis_dummies.parquet")